---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- "**/config/"
- "**/spec/"
- "**/vendor/"
