---
version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 150
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 40 # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: 40 # language-specific defaults. an override will affect all languages.

engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: false

plugins:
  phpcodesniffer:
      enabled: true
      config:
      	standard: "PHPCS"
  sonar-php:
        enabled: true
        config:
          tests_patterns:
            - tests/TestCase/**

ratings:
  paths:
  - "**.php"

exclude_paths:
- "**/config/"
- "**/spec/"
- "**/vendor/"
