language: php

sudo: false

php:
  - 7.0
  - 7.1

services:
  - mysql
  - postgres

before_install:
  - mysql -e 'CREATE DATABASE cake;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

env:
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - sh -c "composer require 'codeclimate/php-test-reporter:dev-master'"
  - phpenv rehash
  - composer install
  - sh -c "vendor/bin/phpcs --config-set installed_paths vendor/cakephp/cakephp-codesniffer"

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=CakePHP ./tests"
  - sh -c "vendor/bin/phpunit"
  - sh -c "vendor/bin/phpunit --coverage-clover build/logs/clover.xml"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
  webhooks:
    urls:
      - DeployWebHook
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never # default: never

addons:
    code_climate:
        repo_token: CodeClimateTokenForReplacement