
language: php

sudo: required

php:
  - 7.0

env: DB=mysql

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash
  - composer install
  - composer update

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./tests"

notifications:
  email: true

addons:
    code_climate:
        repo_token: CodeClimateTokenForReplacement
