language: php

sudo: required

php:
  - 7.0
  - 7.1

env:
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash
  - composer install
  - composer update
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - sh -c "vendor/bin/phpcbf --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./tests"
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./tests"
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
  webhooks:
    urls:
      - DeployWebHook
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never # default: never

addons:
    code_climate:
        repo_token: CodeClimateTokenForReplacement

