language: php

sudo: false

php:
  - 7.0
  - 7.1

env:
  - DB=postgres

services:
  - postgres

before_script:
  - phpenv rehash
  - composer install
  - psql -c 'create database cake;' -U postgres
  - sh -c "bin/cake migrations migrate"
  - sh -c "bin/cake database seed"
  - sh -c "vendor/bin/phpcs --config-set installed_paths vendor/cakephp/cakephp-codesniffer"

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=CakePHP ./tests ./src/Model"
  - sh -c "vendor/bin/phpunit --coverage-clover ./logs/clover.xml"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
  webhooks:
    urls:
      - DeployWebHook
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never # default: never

addons:
    code_climate:
        repo_token: CodeClimateTokenForReplacement