language: php

sudo: false

php:
  - 7.1

env:
  - DB=postgres

services:
  - postgres

before_script:
  - phpenv rehash
  - composer install
  - psql -c 'create database cake;' -U postgres
  - sh -c "bin/cake database build"
  - sh -c "bin/cake database seed"

script:
  - composer cs-check
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/test-reporter

notifications:
  email: true
  webhooks:
    urls:
      - DeployWebHook
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never # default: never

addons:
    code_climate:
        repo_token: CodeClimateTokenForReplacement