language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - DB=postgres
  global:
    - PGPORT=5433

services:
  - postgresql

before_script:
  - cp config/app.travis.php config/app.php
  - cp config/app_DB.travis.php config/app_DB.php
  - phpenv rehash
  - composer install
  - psql -c 'create database cake;' -U postgres
  - psql -c 'create database fake;' -U postgres
  - sh -c "bin/cake database build"
  - sh -c "bin/cake database seed"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer cs-check
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - ./cc-test-reporter after-build --coverage-input-type clover --id CodeClimateTokenForReplacement --exit-code $TRAVIS_TEST_RESULT


notifications:
  email: true
  webhooks:
    urls:
      - DeployWebHook
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never # default: never

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
  code_climate:
      repo_token: CodeClimateTokenForReplacement