<?php

use Migrations\AbstractSeed;

/**
 * Scoutgroups seed.
 */
class ScoutgroupsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'scoutgroup' => 'Silver Leys (Bishop\'s Stortford)',
                'district_id' => '2',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '2',
                'scoutgroup' => 'North Mymms',
                'district_id' => '10',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '3',
                'scoutgroup' => 'Colney Heath Scout and Guide Group',
                'district_id' => '13',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '4',
                'scoutgroup' => 'Markyate',
                'district_id' => '13',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '5',
                'scoutgroup' => 'Redbourn',
                'district_id' => '13',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '6',
                'scoutgroup' => 'Chells (Stevenage)',
                'district_id' => '14',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '7',
                'scoutgroup' => 'Pin Green',
                'district_id' => '14',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '8',
                'scoutgroup' => 'Poplar Scout Group',
                'district_id' => '14',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '9',
                'scoutgroup' => 'St Nicholas (Stevenage)',
                'district_id' => '14',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '10',
                'scoutgroup' => 'Symonds Green',
                'district_id' => '14',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '11',
                'scoutgroup' => 'Buntingford',
                'district_id' => '15',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '12',
                'scoutgroup' => 'Hunsdon',
                'district_id' => '15',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '13',
                'scoutgroup' => 'Ridgeway',
                'district_id' => '18',
                'number_stripped' => '0',
                'deleted' => null,
            ],
            [
                'id' => '14',
                'scoutgroup' => '1st Ashwell',
                'district_id' => '1',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '15',
                'scoutgroup' => '1st Baldock',
                'district_id' => '1',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '16',
                'scoutgroup' => '1st Bishops Stortford and Hockerill',
                'district_id' => '2',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '17',
                'scoutgroup' => '1st Much Hadham',
                'district_id' => '2',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '18',
                'scoutgroup' => '1st Sawbridgeworth',
                'district_id' => '2',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '19',
                'scoutgroup' => '1st St Michael\'s Mead',
                'district_id' => '2',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '20',
                'scoutgroup' => '1st Thorley (St James)',
                'district_id' => '2',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '21',
                'scoutgroup' => '1st Broxbourne',
                'district_id' => '3',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '22',
                'scoutgroup' => '1st Cheshunt',
                'district_id' => '3',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '23',
                'scoutgroup' => '1st Hammond Street',
                'district_id' => '3',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '24',
                'scoutgroup' => '1st Turnford (St Clements)',
                'district_id' => '3',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '25',
                'scoutgroup' => '1st Wormley',
                'district_id' => '3',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '26',
                'scoutgroup' => '1st/2nd Waltham Cross Holy Trinity',
                'district_id' => '3',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '27',
                'scoutgroup' => '1st Elstree and Borehamwood',
                'district_id' => '4',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '28',
                'scoutgroup' => '1st Radlett',
                'district_id' => '4',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '29',
                'scoutgroup' => '1st Shenley',
                'district_id' => '4',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '30',
                'scoutgroup' => '1st Harpenden (Methodist)',
                'district_id' => '5',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '31',
                'scoutgroup' => '1st Kimpton',
                'district_id' => '5',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '32',
                'scoutgroup' => '1st Wheathampstead',
                'district_id' => '5',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '33',
                'scoutgroup' => '1st Apsley',
                'district_id' => '6',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '34',
                'scoutgroup' => '1st Bennetts End',
                'district_id' => '6',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '35',
                'scoutgroup' => '1st Bovingdon',
                'district_id' => '6',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '36',
                'scoutgroup' => '1st Hemel Hempstead',
                'district_id' => '6',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '37',
                'scoutgroup' => '1st Kings Langley',
                'district_id' => '6',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '38',
                'scoutgroup' => '1st Leverstock Green',
                'district_id' => '6',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '39',
                'scoutgroup' => '1st Warners End',
                'district_id' => '6',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '40',
                'scoutgroup' => '1st Hertford Heath',
                'district_id' => '7',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '41',
                'scoutgroup' => '1st Hertford Scout Group',
                'district_id' => '7',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '42',
                'scoutgroup' => '1st Letty Green',
                'district_id' => '7',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '43',
                'scoutgroup' => '1st Watton-at-Stone',
                'district_id' => '7',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '44',
                'scoutgroup' => '1st Codicote',
                'district_id' => '9',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '45',
                'scoutgroup' => '1st Welwyn',
                'district_id' => '9',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '46',
                'scoutgroup' => '1st Welwyn Garden City (St Francis)',
                'district_id' => '9',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '47',
                'scoutgroup' => '1st Cuffley',
                'district_id' => '10',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '48',
                'scoutgroup' => '1st Little Heath & Potters Bar',
                'district_id' => '10',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '49',
                'scoutgroup' => '1st Northaw',
                'district_id' => '10',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '50',
                'scoutgroup' => '1st Chorleywood (8th Rickmansworth & Chorleywood)',
                'district_id' => '11',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '51',
                'scoutgroup' => '1st Rickmansworth & Chorleywood',
                'district_id' => '11',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '52',
                'scoutgroup' => '1st Harston',
                'district_id' => '12',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '53',
                'scoutgroup' => '1st Orwell',
                'district_id' => '12',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '54',
                'scoutgroup' => '1st Royston',
                'district_id' => '12',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '55',
                'scoutgroup' => '1st Flamstead',
                'district_id' => '13',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '56',
                'scoutgroup' => '1st London Colney',
                'district_id' => '13',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '57',
                'scoutgroup' => '1st Park Street',
                'district_id' => '13',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '58',
                'scoutgroup' => '1st Sandridge',
                'district_id' => '13',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '59',
                'scoutgroup' => '1st St Albans Scout Group',
                'district_id' => '13',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '60',
                'scoutgroup' => '1st Knebworth (Earl of Lyttons Own)',
                'district_id' => '14',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '61',
                'scoutgroup' => '1st Stevenage',
                'district_id' => '14',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '62',
                'scoutgroup' => '1st Braughing',
                'district_id' => '15',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '63',
                'scoutgroup' => '1st Great Amwell',
                'district_id' => '15',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '64',
                'scoutgroup' => '1st Stanstead Abbotts & St. Margaret\'s',
                'district_id' => '15',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '65',
                'scoutgroup' => '1st North Watford',
                'district_id' => '16',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '66',
                'scoutgroup' => '1st Bushey Heath Scout Group',
                'district_id' => '17',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '67',
                'scoutgroup' => '1st Watford South (Countess of Claredons Own)',
                'district_id' => '17',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '68',
                'scoutgroup' => '1st Berkhamsted',
                'district_id' => '18',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '69',
                'scoutgroup' => '1st Gossoms End - Berkhamsted',
                'district_id' => '18',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '70',
                'scoutgroup' => '1st Little Gaddesden',
                'district_id' => '18',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '71',
                'scoutgroup' => '1st Northchurch',
                'district_id' => '18',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '72',
                'scoutgroup' => '1st Potten End',
                'district_id' => '18',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '73',
                'scoutgroup' => '1st Tring',
                'district_id' => '18',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '74',
                'scoutgroup' => '1st Wilstone & Long Marston',
                'district_id' => '18',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '75',
                'scoutgroup' => '2nd Baldock',
                'district_id' => '1',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '76',
                'scoutgroup' => '2nd Cheshunt (St Mary the Virgin)',
                'district_id' => '3',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '77',
                'scoutgroup' => '2nd Goffs Oak (Methodist)',
                'district_id' => '3',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '78',
                'scoutgroup' => '2nd Hoddesdon',
                'district_id' => '3',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '79',
                'scoutgroup' => '2nd Harpenden',
                'district_id' => '5',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '80',
                'scoutgroup' => '2nd Hemel Hempstead (Grove Hill)',
                'district_id' => '6',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '81',
                'scoutgroup' => '2nd Bengeo',
                'district_id' => '7',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '82',
                'scoutgroup' => '2nd Hitchin (Air Scouts)',
                'district_id' => '8',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '83',
                'scoutgroup' => '2nd Welwyn (Oaklands)',
                'district_id' => '9',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '84',
                'scoutgroup' => '2nd\\7th Welwyn Garden City',
                'district_id' => '9',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '85',
                'scoutgroup' => '2nd Little Heath (Christ Church)',
                'district_id' => '10',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '86',
                'scoutgroup' => '2nd Rickmansworth & Chorleywood Batchworth S.S.',
                'district_id' => '11',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '87',
                'scoutgroup' => '2nd St Albans',
                'district_id' => '13',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '88',
                'scoutgroup' => '2nd Datchworth',
                'district_id' => '14',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '89',
                'scoutgroup' => '2nd Ware (St. Mary\'s)',
                'district_id' => '15',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '90',
                'scoutgroup' => '2nd North Watford',
                'district_id' => '16',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '91',
                'scoutgroup' => '2nd Bushey & Oxhey (2nd Oxhey)',
                'district_id' => '17',
                'number_stripped' => '2',
                'deleted' => null,
            ],
            [
                'id' => '92',
                'scoutgroup' => '3rd Hoddesdon',
                'district_id' => '3',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '93',
                'scoutgroup' => '3rd Waltham Cross (St Joseph\'s)',
                'district_id' => '3',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '94',
                'scoutgroup' => '3rd Elstree & Borehamwood',
                'district_id' => '4',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '95',
                'scoutgroup' => '3rd Harpenden',
                'district_id' => '5',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '96',
                'scoutgroup' => '3rd Boxmoor',
                'district_id' => '6',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '97',
                'scoutgroup' => '3rd Hertford',
                'district_id' => '7',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '98',
                'scoutgroup' => '3rd Hitchin (Walsworth Road Baptist)',
                'district_id' => '8',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '99',
                'scoutgroup' => '3rd Hatfield Air Scouts',
                'district_id' => '9',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '100',
                'scoutgroup' => '3rd/9th Welwyn Garden City',
                'district_id' => '9',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '101',
                'scoutgroup' => '3rd Potters Bar',
                'district_id' => '10',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '102',
                'scoutgroup' => '3rd Rickmansworth & Chorleywood Croxley Green',
                'district_id' => '11',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '103',
                'scoutgroup' => '3rd St Albans',
                'district_id' => '13',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '104',
                'scoutgroup' => '3rd Ware',
                'district_id' => '15',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '105',
                'scoutgroup' => '3rd North Watford (1st Abbots Langley)',
                'district_id' => '16',
                'number_stripped' => '3',
                'deleted' => null,
            ],
            [
                'id' => '106',
                'scoutgroup' => '4th Letchworth (St Pauls)',
                'district_id' => '1',
                'number_stripped' => '4',
                'deleted' => null,
            ],
            [
                'id' => '107',
                'scoutgroup' => '4th Radlett',
                'district_id' => '4',
                'number_stripped' => '4',
                'deleted' => null,
            ],
            [
                'id' => '108',
                'scoutgroup' => '4th Harpenden',
                'district_id' => '5',
                'number_stripped' => '4',
                'deleted' => null,
            ],
            [
                'id' => '109',
                'scoutgroup' => '4th Boxmoor (St.Mary & St.Joseph)',
                'district_id' => '6',
                'number_stripped' => '4',
                'deleted' => null,
            ],
            [
                'id' => '110',
                'scoutgroup' => '4th Hemel Hempstead',
                'district_id' => '6',
                'number_stripped' => '4',
                'deleted' => null,
            ],
            [
                'id' => '111',
                'scoutgroup' => '4th Hitchin St Ippolyts Church',
                'district_id' => '8',
                'number_stripped' => '4',
                'deleted' => null,
            ],
            [
                'id' => '112',
                'scoutgroup' => '4th Potters Bar',
                'district_id' => '10',
                'number_stripped' => '4',
                'deleted' => null,
            ],
            [
                'id' => '113',
                'scoutgroup' => '4th St. Albans',
                'district_id' => '13',
                'number_stripped' => '4',
                'deleted' => null,
            ],
            [
                'id' => '114',
                'scoutgroup' => '4th North Watford (1st Bricket Wood)',
                'district_id' => '16',
                'number_stripped' => '4',
                'deleted' => null,
            ],
            [
                'id' => '115',
                'scoutgroup' => '5th Letchworth',
                'district_id' => '1',
                'number_stripped' => '5',
                'deleted' => null,
            ],
            [
                'id' => '116',
                'scoutgroup' => '5th Hoddesdon',
                'district_id' => '3',
                'number_stripped' => '5',
                'deleted' => null,
            ],
            [
                'id' => '117',
                'scoutgroup' => '5th Harpenden Scout Group',
                'district_id' => '5',
                'number_stripped' => '5',
                'deleted' => null,
            ],
            [
                'id' => '118',
                'scoutgroup' => '5th Hitchin (St. Mark\'s)',
                'district_id' => '8',
                'number_stripped' => '5',
                'deleted' => null,
            ],
            [
                'id' => '119',
                'scoutgroup' => '5th Potters Bar',
                'district_id' => '10',
                'number_stripped' => '5',
                'deleted' => null,
            ],
            [
                'id' => '120',
                'scoutgroup' => '5th/13th St. Albans',
                'district_id' => '13',
                'number_stripped' => '5',
                'deleted' => null,
            ],
            [
                'id' => '121',
                'scoutgroup' => '5th Stevenage Air Scouts',
                'district_id' => '14',
                'number_stripped' => '5',
                'deleted' => null,
            ],
            [
                'id' => '122',
                'scoutgroup' => '5th Ware (Christ Church)',
                'district_id' => '15',
                'number_stripped' => '5',
                'deleted' => null,
            ],
            [
                'id' => '123',
                'scoutgroup' => '5th North Watford (1st.Langleybury)',
                'district_id' => '16',
                'number_stripped' => '5',
                'deleted' => null,
            ],
            [
                'id' => '124',
                'scoutgroup' => '6th Hitchin (Priory)',
                'district_id' => '8',
                'number_stripped' => '6',
                'deleted' => null,
            ],
            [
                'id' => '125',
                'scoutgroup' => '6th Welwyn Garden City',
                'district_id' => '9',
                'number_stripped' => '6',
                'deleted' => null,
            ],
            [
                'id' => '126',
                'scoutgroup' => '6th Rickmansworth & Chorleywood Sea Scouts',
                'district_id' => '11',
                'number_stripped' => '6',
                'deleted' => null,
            ],
            [
                'id' => '127',
                'scoutgroup' => '6th North Watford',
                'district_id' => '16',
                'number_stripped' => '6',
                'deleted' => null,
            ],
            [
                'id' => '128',
                'scoutgroup' => '7th Letchworth (St Thomas A\'Becket)',
                'district_id' => '1',
                'number_stripped' => '7',
                'deleted' => null,
            ],
            [
                'id' => '129',
                'scoutgroup' => '7th Borehamwood',
                'district_id' => '4',
                'number_stripped' => '7',
                'deleted' => null,
            ],
            [
                'id' => '130',
                'scoutgroup' => '7th Hemel Hempstead (Lockers Park) Scout Group',
                'district_id' => '6',
                'number_stripped' => '7',
                'deleted' => null,
            ],
            [
                'id' => '131',
                'scoutgroup' => '7th Hitchin (Our Lady\'s)',
                'district_id' => '8',
                'number_stripped' => '7',
                'deleted' => null,
            ],
            [
                'id' => '132',
                'scoutgroup' => '7th Hatfield (South)',
                'district_id' => '9',
                'number_stripped' => '7',
                'deleted' => null,
            ],
            [
                'id' => '133',
                'scoutgroup' => '7th Royston (Barkway)',
                'district_id' => '12',
                'number_stripped' => '7',
                'deleted' => null,
            ],
            [
                'id' => '134',
                'scoutgroup' => '7th Stevenage Sea Scouts',
                'district_id' => '14',
                'number_stripped' => '7',
                'deleted' => null,
            ],
            [
                'id' => '135',
                'scoutgroup' => '7th Bushey & Oxhey (1st Bushey)',
                'district_id' => '17',
                'number_stripped' => '7',
                'deleted' => null,
            ],
            [
                'id' => '136',
                'scoutgroup' => '8th Letchworth',
                'district_id' => '1',
                'number_stripped' => '8',
                'deleted' => null,
            ],
            [
                'id' => '137',
                'scoutgroup' => '8th Hitchin (Oughton)Scout Group',
                'district_id' => '8',
                'number_stripped' => '8',
                'deleted' => null,
            ],
            [
                'id' => '138',
                'scoutgroup' => '9th Harpenden',
                'district_id' => '5',
                'number_stripped' => '9',
                'deleted' => null,
            ],
            [
                'id' => '139',
                'scoutgroup' => '9th Hitchin (1st Ickleford)',
                'district_id' => '8',
                'number_stripped' => '9',
                'deleted' => null,
            ],
            [
                'id' => '140',
                'scoutgroup' => '9th Rickmansworth & Chorleywood 1st Mill End',
                'district_id' => '11',
                'number_stripped' => '9',
                'deleted' => null,
            ],
            [
                'id' => '141',
                'scoutgroup' => '9th St. Albans',
                'district_id' => '13',
                'number_stripped' => '9',
                'deleted' => null,
            ],
            [
                'id' => '142',
                'scoutgroup' => '9th North Watford (Woodside)',
                'district_id' => '16',
                'number_stripped' => '9',
                'deleted' => null,
            ],
            [
                'id' => '143',
                'scoutgroup' => '10th Bishop\'s Stortford (St. Joseph\'s)',
                'district_id' => '2',
                'number_stripped' => '10',
                'deleted' => null,
            ],
            [
                'id' => '144',
                'scoutgroup' => '10th Harpenden (Methodist)',
                'district_id' => '5',
                'number_stripped' => '10',
                'deleted' => null,
            ],
            [
                'id' => '145',
                'scoutgroup' => '10th Royston',
                'district_id' => '12',
                'number_stripped' => '10',
                'deleted' => null,
            ],
            [
                'id' => '146',
                'scoutgroup' => '11th Letchworth',
                'district_id' => '1',
                'number_stripped' => '11',
                'deleted' => null,
            ],
            [
                'id' => '147',
                'scoutgroup' => '11th Hitchin (Christchurch)',
                'district_id' => '8',
                'number_stripped' => '11',
                'deleted' => null,
            ],
            [
                'id' => '148',
                'scoutgroup' => '11th Welwyn Garden City (Attimore) Scout Group',
                'district_id' => '9',
                'number_stripped' => '11',
                'deleted' => null,
            ],
            [
                'id' => '149',
                'scoutgroup' => '12th Letchworth',
                'district_id' => '1',
                'number_stripped' => '12',
                'deleted' => null,
            ],
            [
                'id' => '150',
                'scoutgroup' => '12th Harpenden (St Nicholas)',
                'district_id' => '5',
                'number_stripped' => '12',
                'deleted' => null,
            ],
            [
                'id' => '151',
                'scoutgroup' => '12th Hitchin (St Mary)',
                'district_id' => '8',
                'number_stripped' => '12',
                'deleted' => null,
            ],
            [
                'id' => '152',
                'scoutgroup' => '12th Rickmansworth and Chorleywood - 1st Sarratt',
                'district_id' => '11',
                'number_stripped' => '12',
                'deleted' => null,
            ],
            [
                'id' => '153',
                'scoutgroup' => '14th Bushey & Oxhey Sea Scout Group',
                'district_id' => '17',
                'number_stripped' => '14',
                'deleted' => null,
            ],
            [
                'id' => '154',
                'scoutgroup' => '15th Hitchin (Holwell & Pirton)',
                'district_id' => '8',
                'number_stripped' => '15',
                'deleted' => null,
            ],
            [
                'id' => '155',
                'scoutgroup' => '15th Bushey & Oxhey',
                'district_id' => '17',
                'number_stripped' => '15',
                'deleted' => null,
            ],
            [
                'id' => '156',
                'scoutgroup' => '16th Hitchin (St Faiths)',
                'district_id' => '8',
                'number_stripped' => '16',
                'deleted' => null,
            ],
            [
                'id' => '157',
                'scoutgroup' => '16th St Albans',
                'district_id' => '13',
                'number_stripped' => '16',
                'deleted' => null,
            ],
            [
                'id' => '158',
                'scoutgroup' => '16th Watford South Scout Group',
                'district_id' => '17',
                'number_stripped' => '16',
                'deleted' => null,
            ],
            [
                'id' => '159',
                'scoutgroup' => '17th Hitchin',
                'district_id' => '8',
                'number_stripped' => '17',
                'deleted' => null,
            ],
            [
                'id' => '160',
                'scoutgroup' => '17th St Albans (Abbey)',
                'district_id' => '13',
                'number_stripped' => '17',
                'deleted' => null,
            ],
            [
                'id' => '161',
                'scoutgroup' => '18th St Albans',
                'district_id' => '13',
                'number_stripped' => '18',
                'deleted' => null,
            ],
            [
                'id' => '162',
                'scoutgroup' => '22nd Watford South Scout Group',
                'district_id' => '17',
                'number_stripped' => '22',
                'deleted' => null,
            ],
            [
                'id' => '163',
                'scoutgroup' => '29th Watford South (Methodist)',
                'district_id' => '17',
                'number_stripped' => '29',
                'deleted' => null,
            ],
            [
                'id' => '164',
                'scoutgroup' => '30th Watford South (St Mary\'s)',
                'district_id' => '17',
                'number_stripped' => '30',
                'deleted' => null,
            ],
            [
                'id' => '165',
                'scoutgroup' => '53rd Watford (St. Peter\'s)',
                'district_id' => '17',
                'number_stripped' => '53',
                'deleted' => null,
            ],
            [
                'id' => '166',
                'scoutgroup' => '61st Watford',
                'district_id' => '17',
                'number_stripped' => '61',
                'deleted' => null,
            ],
            [
                'id' => '167',
                'scoutgroup' => '64th Bushey and Oxhey 3rd Bushey',
                'district_id' => '17',
                'number_stripped' => '64',
                'deleted' => null,
            ],
            [
                'id' => '168',
                'scoutgroup' => '72nd Watford South',
                'district_id' => '17',
                'number_stripped' => '72',
                'deleted' => null,
            ],
            [
                'id' => '169',
                'scoutgroup' => '79th Bushey and Oxhey',
                'district_id' => '17',
                'number_stripped' => '79',
                'deleted' => null,
            ],
            [
                'id' => '170',
                'scoutgroup' => 'The Mordens (6th Royston Air Scouts)',
                'district_id' => '12',
                'number_stripped' => '6',
                'deleted' => null,
            ],
            [
                'id' => '171',
                'scoutgroup' => '74th Watford South (St. Luke\'s)',
                'district_id' => '17',
                'number_stripped' => '74',
                'deleted' => null,
            ],
            [
                'id' => '174',
                'scoutgroup' => '1st Mill End',
                'district_id' => '11',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '175',
                'scoutgroup' => '1st Gadebridge Scout Group',
                'district_id' => '6',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '176',
                'scoutgroup' => '5th Hemel Hempstead (Adeyfield Free Church) ',
                'district_id' => '6',
                'number_stripped' => '5',
                'deleted' => null,
            ],
            [
                'id' => '177',
                'scoutgroup' => '1st Hertford',
                'district_id' => '7',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '178',
                'scoutgroup' => '1st Hitchin Boys Grammar School',
                'district_id' => '8',
                'number_stripped' => '1',
                'deleted' => null,
            ],
            [
                'id' => '179',
                'scoutgroup' => '8th North Watford (1st Garston)',
                'district_id' => '16',
                'number_stripped' => '8',
                'deleted' => null,
            ],
            [
                'id' => '180',
                'scoutgroup' => '11th North Watford',
                'district_id' => '16',
                'number_stripped' => '11',
                'deleted' => null,
            ],
        ];

        $table = $this->table('scoutgroups');
        $table->insert($data)->save();
    }
}
